// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs4-25r8iD0t9l1uyA6r_Nm1tR6JwIZbw',
    appId: '1:188808536595:web:b04bbe7a8badfd7511d5e6',
    messagingSenderId: '188808536595',
    projectId: 'next-play-b8372',
    authDomain: 'next-play-b8372.firebaseapp.com',
    storageBucket: 'next-play-b8372.firebasestorage.app',
    measurementId: 'G-MCD9FB191Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqRLy5yML-P6tH6EudG6g-ntESmsPW8sU',
    appId: '1:188808536595:android:92b0ac013dfec09311d5e6',
    messagingSenderId: '188808536595',
    projectId: 'next-play-b8372',
    storageBucket: 'next-play-b8372.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQlOvW_cl5jG6riaLydS-wbqUw_eYBCYs',
    appId: '1:188808536595:ios:ef54e6e31201b67111d5e6',
    messagingSenderId: '188808536595',
    projectId: 'next-play-b8372',
    storageBucket: 'next-play-b8372.firebasestorage.app',
    iosClientId: '188808536595-nfrnp5vhbergsqf5q7vpj09kcj2h3l5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextPlay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQlOvW_cl5jG6riaLydS-wbqUw_eYBCYs',
    appId: '1:188808536595:ios:ef54e6e31201b67111d5e6',
    messagingSenderId: '188808536595',
    projectId: 'next-play-b8372',
    storageBucket: 'next-play-b8372.firebasestorage.app',
    iosClientId: '188808536595-nfrnp5vhbergsqf5q7vpj09kcj2h3l5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextPlay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs4-25r8iD0t9l1uyA6r_Nm1tR6JwIZbw',
    appId: '1:188808536595:web:3617124b632aefff11d5e6',
    messagingSenderId: '188808536595',
    projectId: 'next-play-b8372',
    authDomain: 'next-play-b8372.firebaseapp.com',
    storageBucket: 'next-play-b8372.firebasestorage.app',
    measurementId: 'G-187Q77ZY5V',
  );
}
